### ISSUE TITLE
When access is denied while trying to remove a key, an AttributeError is raised

### ISSUE THREAD

**Issue by iTaybb** [rfk/regobj#4]
When you try to remove a key with unprivilaged user, you should get an access denied error (WindowsError(5, 'Access is denied')). However regobj returns AttributeError and says that the key does not exist:

```
>>> print regobj.HKCR.mp3file.shell.iQuality
<regobj Key 'HKEY_CLASSES_ROOT\mp3file\shell\iQuality'>
>>> del regobj.HKCR.mp3file.shell.iQuality
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\regobj.py", line 384, in __delattr__
    self.del_subkey(name)
  File "C:\Python27\lib\site-packages\regobj.py", line 306, in del_subkey
    subkey = self.get_subkey(name)
  File "C:\Python27\lib\site-packages\regobj.py", line 251, in get_subkey
    raise AttributeError("subkey '%s' does not exist" % (name,))
AttributeError: subkey 'iQuality' does not exist
>>>
```

Got it on Python 2.7.3, regobj 0.2.2, Windows 7 SP1, while running python without administrator permissions.

**Comment by rfk** [comment]
Thanks for reaching out. Unfortunately I am no longer actively maintaining this project, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
